/* Separate modes: SCORM LMS OR explicitly requested loopback xAPI lab; preview sends nothing. */
window.Tracker=(()=>{let api=null,active=false,failed=false,token=null,queue=[],receipts=[],busy=false,ended=false;const started=Date.now();
const status=t=>{const el=document.querySelector('#tracking');if(el)el.textContent=t;const b=document.querySelector('#retry-delivery');if(b)b.hidden=!queue.length;};
function find(w){for(let i=0;i<12;i++){try{if(w.API)return w.API;if(w.parent===w)break;w=w.parent;}catch{break;}}return null;}
function call(fn,...args){try{const v=api[fn](...args);if(v==='false'||(fn==='LMSGetValue'&&api.LMSGetLastError()!=='0'))throw Error('LMS error');return v;}catch{failed=true;status('LMS communication failed · progress may not be saved');return null;}}
async function flush(){if(busy||!token)return;busy=true;try{while(queue.length){const e=queue[0];const r=await fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json','X-Session-Token':token},body:JSON.stringify(e)});if(!r.ok)throw Error();const got=await r.json();if(!got.stored)throw Error();receipts.push({...got,verb:e.verb});queue.shift();}status('Local lab · '+receipts.length+' records stored');}catch{status('Tracking pending · keep this tab open and retry');}finally{busy=false;}}
function event(verb,activity='course',result){if(!token)return;queue.push({id:crypto.randomUUID(),course:COURSE.id,verb,activity,...(result?{result}:{})});flush();}
return {get mode(){return active?'scorm':token?'lab':'preview';},get receipts(){return receipts;},get pending(){return queue.length;},async init(){api=find(window);if(!api&&window.opener)api=find(window.opener);if(api){active=call('LMSInitialize','')==='true';if(active){const st=call('LMSGetValue','cmi.core.lesson_status');if(!st||st==='not attempted')call('LMSSetValue','cmi.core.lesson_status','incomplete');status('LMS connected');let state;try{state=JSON.parse(call('LMSGetValue','cmi.suspend_data')||'null');}catch{}return state;}}if(new URLSearchParams(location.search).get('tracking')==='lab'&&['localhost','127.0.0.1'].includes(location.hostname)){try{const r=await fetch('/api/session',{method:'POST'});if(!r.ok)throw Error();token=(await r.json()).token;event('initialized');}catch{status('Local tracking unavailable · no records sent');}}return null;},event,retry:flush,save(s){if(!active||ended)return;failed=false;const safe={v:1,course:COURSE.id,step:s.step,seen:s.seen,practice:s.practice,answers:s.answers,attempts:s.attempts};call('LMSSetValue','cmi.core.lesson_location',String(s.step));call('LMSSetValue','cmi.suspend_data',JSON.stringify(safe));if(call('LMSCommit','')==='true'&&!failed)status('LMS progress saved · writing excluded');},score(n){if(active){call('LMSSetValue','cmi.core.score.min','0');call('LMSSetValue','cmi.core.score.max','100');call('LMSSetValue','cmi.core.score.raw',String(n));}event(n>=80?'passed':'failed','check',{score:{raw:n,min:0,max:100,scaled:n/100},success:n>=80});},complete(){if(active)call('LMSSetValue','cmi.core.lesson_status','completed');event('completed','course',{completion:true});},finish(){if(!active||ended)return;let sec=Math.floor((Date.now()-started)/1000);const h=String(Math.floor(sec/3600)).padStart(2,'0'),m=String(Math.floor(sec%3600/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');call('LMSSetValue','cmi.core.session_time',h+':'+m+':'+s);call('LMSSetValue','cmi.core.exit','suspend');call('LMSCommit','');call('LMSFinish','');ended=true;}};})();
window.addEventListener('pagehide',()=>Tracker.finish());
