(()=>{'use strict';const c=COURSE,$=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[a]));
const labels=['Welcome','The work problem','Watch & explore','Try the review desk','Practice a decision','Create your response','Check your decisions','Results and review','Take it to work','Lesson wrap-up'];let s={step:0,seen:[],practice:null,answers:[null,null,null,null,null],attempts:[],draft:'',criteria:[],exported:false},qi=0,trigger=null;
const seen=n=>s.seen.includes(n),mark=n=>{if(!seen(n))s.seen.push(n);},list=a=>'<ul>'+a.map(v=>'<li>'+esc(v)+'</li>').join('')+'</ul>';
const choices=(q,name,sel)=>'<fieldset><legend>'+esc(q.prompt)+'</legend>'+q.options.map((o,i)=>'<label class="choice"><input type="radio" name="'+name+'" value="'+i+'" '+(sel===i?'checked':'')+'><span>'+esc(o)+'</span></label>').join('')+'</fieldset>';
function modal(html){trigger=document.activeElement;$('#dialog-content').innerHTML=html;$('#dialog').showModal();}$('#close').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('close',()=>trigger?.focus());
const nav=()=>labels.map((v,i)=>'<button data-go="'+i+'" '+(i===s.step?'aria-current="step"':'')+'>'+String(i+1).padStart(2,'0')+' '+(seen(i)?'✓ ':'')+esc(v)+'</button>').join('');
function error(t){$('#error').textContent=t;$('#error').focus();}function feedback(t){$('#feedback').innerHTML='<div class="feedback" tabindex="-1">'+esc(t)+'</div>';$('.feedback').focus();}
function body(){switch(s.step){case 0:return '<div class="hero"><div><p class="eyebrow">'+esc(c.creative.series)+'</p><h1>'+esc(c.headline).replace('\n','<br>')+'</h1><p class="intro">'+esc(c.title)+'</p><p class="meta">'+esc(c.duration)+' · 10 steps · Learn by doing</p><button class="primary" data-next>Begin lesson</button><p class="meta">For '+esc(c.audience.toLowerCase())+'.</p></div>'+c.hero+'</div><div class="card"><h2>What you will practice</h2>'+list(c.outcomes)+'</div><p class="meta">'+esc(c.disclosure)+'</p>';
case 1:return '<h1>A routine review. A consequential choice.</h1><div class="mission-scene"><div class="mission-number">02<span>HOURS TO EXPLAIN</span></div><div><p class="eyebrow">YOUR ASSIGNMENT</p><h2>A time sheet is waiting for approval.</h2><p>Compare the claim with its supporting record. Decide whether the evidence supports approval.</p><p><b>You’ll inspect → decide → explain.</b></p><button data-go="3" class="primary">Open the review desk →</button><p class="meta">Need a demonstration first? Continue to Watch & explore.</p></div></div>';
case 2:return '<h1>See the review in action.</h1><h2 class="concept-heading">Keep these decision rules close.</h2><button id="expand">Expand all</button>'+c.concepts.map(v=>'<details><summary>'+esc(v.title)+'</summary><p>'+esc(v.body)+'</p></details>').join('');
case 3:return '<h1>Inspect. Decide. Explain.</h1><details class="worked-debrief"><summary>Open the worked explanation</summary><p>'+esc(c.example.body)+'</p><ol>'+c.example.steps.map(v=>'<li>'+esc(v)+'</li>').join('')+'</ol></details>';
case 4:return '<h1>Make the next decision.</h1><div class="card">'+choices(c.practice,'practice',s.practice)+'<button id="practice" class="primary">Check my choice</button><div id="feedback">'+(s.practice!==null?'<div class="feedback">'+esc(c.practice.feedback)+'</div>':'')+'</div></div>';
case 5:return '<h1>Create something useful.</h1><p class="intro">'+esc(c.draft.prompt)+'</p><div class="grid"><div class="card"><label for="draft"><strong>'+esc(c.draft.label)+'</strong></label><textarea id="draft" maxlength="2500">'+esc(s.draft)+'</textarea><p class="meta">Use fictional information. Writing stays in this tab, is excluded from tracking and is lost on refresh. Download it to keep it.</p><button id="download">Download my response</button><details><summary>See a possible response</summary><p>'+esc(c.draft.model)+'</p></details></div><div class="card checklist"><h2>Review your response</h2><p class="meta">Self-review only. This is not an automatic quality score.</p>'+c.draft.criteria.map((v,i)=>'<label><input type="checkbox" data-criterion="'+i+'" '+(s.criteria.includes(i)?'checked':'')+'>'+esc(v)+'</label>').join('')+'<p>Revise until you can affirm each criterion. A human reviewer is still needed to verify quality.</p></div></div>';
case 6:return '<h1>Check your decisions.</h1><p class="meta">Question '+(qi+1)+' of 5 · Target 4/5 · Feedback after submission</p><div class="card">'+choices(c.quiz[qi],'quiz',s.answers[qi])+'<div class="actions">'+(qi?'<button id="previous-question">Previous question</button>':'')+'<button class="primary" id="question-next">'+(qi===4?'Submit all answers':'Next question')+'</button></div></div>';
case 7:if(!s.attempts.length)return '<h1>Your results will appear here.</h1><button data-go="6" class="primary">Open the check</button>';return '<h1>Reflect. Refine. Try again.</h1><div class="grid"><div class="card dark"><div class="score">'+s.attempts.at(-1).score+'%</div><p>'+ (s.attempts.at(-1).score>=80?'Knowledge-check target met':'Review recommended')+'</p><p>First: '+s.attempts[0].score+'% · Latest: '+s.attempts.at(-1).score+'%</p><p>Attempt '+s.attempts.length+'</p></div><div class="card"><h2>Keep the evidence distinct.</h2><p>The check measures decisions in these cases. Your writing is self-reviewed; it has not been independently assessed.</p><button id="retry">Retry the check</button> <button data-go="2">Review concepts</button></div></div>'+c.quiz.map((v,i)=>'<details><summary>Q'+(i+1)+' · '+(s.attempts.at(-1).answers[i]===v.key?'Correct':'Review')+'</summary><p>'+esc(v.prompt)+'</p><p><strong>'+esc(v.options[v.key])+'</strong></p><p>'+esc(v.feedback)+'</p></details>').join('');
case 8:return '<h1>Take it into your work.</h1><div class="card"><h2>Your quick checklist</h2>'+list(c.jobaid)+'<button id="jobaid">Download checklist</button></div><p class="notice">Choose one future work example and ask a peer or manager to review it against these criteria. A completed sample is not evidence of sustained workplace performance.</p>';
case 9:{const missing=labels.map((v,i)=>i<9&&!seen(i)?i:null).filter(v=>v!==null);return '<h1>'+(missing.length?'A few steps remain.':'Make the learning visible.')+'</h1>'+ (missing.length?'<p>Finish these required activities:</p>'+missing.map(i=>'<p><button data-go="'+i+'">'+esc(labels[i])+'</button></p>').join(''):'<div class="card"><h2>Sample reviewed</h2><p>Knowledge-check result: '+s.attempts.at(-1)?.score+'%.</p><p>Written response: self-reviewed. No certification or independent competence claim.</p><button id="download">Download my response</button></div>')+'<p class="notice">'+(Tracker.mode==='preview'?'Preview mode: no learning records sent.':Tracker.mode==='lab'?'Local lab mode: inspect the delivery status for stored records.':'LMS mode: completion records participation; score is separate. Free text is never saved to the LMS.')+'</p>';}}}
function render(focus=true){$('#rail').innerHTML=nav();$('#main').innerHTML='<div class="fade"><p class="eyebrow">'+esc(c.title)+'</p>'+body()+'<p id="error" tabindex="-1" role="alert"></p>'+(s.step&&s.step!==9?'<div class="bottom"><button data-back>Back</button><span class="meta">Step '+(s.step+1)+' of 10</span>'+(s.step!==6?'<button data-next class="primary">'+(s.step===8?'Finish the lesson':'Continue')+'</button>':'')+'</div>':'')+'</div>';Experience.reset();Experience.mount(s.step);$('#progress').value=s.seen.length;$('#progress-text').textContent=s.seen.length+' of 10 steps reviewed';if(focus){$('#main').focus();window.scrollTo(0,0);}Tracker.save(s);}
function go(n){s.step=n;if(n===9&&Array.from({length:9},(_,i)=>seen(i)).every(Boolean)&&!seen(9)){mark(9);Tracker.complete();}render();Tracker.event('experienced','step-'+n);}
function next(){if(s.step===4&&s.practice===null)return error('Choose an answer and check it first.');if(s.step===5){if(!s.draft.trim()||s.criteria.length!==4)return error('Write your response and review all four criteria.');if(!s.exported){modal('<h2>Keep your writing</h2><p>Your response remains only in this tab. Download it to keep it after closing or refreshing.</p><button id="keep-tab">Continue with writing in this tab</button>');return;}}if(s.step===7&&!s.attempts.length)return error('Submit the five-question check first.');mark(s.step);go(Math.min(s.step+1,9));}
function download(text,name){const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-go')){if($('#dialog').open)$('#dialog').close();return go(Number(b.dataset.go));}if(b.hasAttribute('data-next'))return next();if(b.hasAttribute('data-back'))return go(s.step-1);switch(b.id){case 'menu':return modal('<h2>Lesson menu</h2><nav>'+nav()+'</nav>');case 'resources':return modal('<h2>Your toolkit</h2>'+list(c.jobaid)+'<h3>References</h3><ul>'+c.sources.map(v=>'<li><a href="'+esc(v[1])+'" target="_blank" rel="noopener">'+esc(v[0])+'</a></li>').join('')+'</ul><p>Sources reviewed 9 October 2026. Verify tenant-specific instructions before real work.</p>');case 'preferences':return modal('<h2>Reading preferences</h2><label><input id="large" type="checkbox" '+(document.body.classList.contains('large')?'checked':'')+'> Larger text</label><label><input id="reduced" type="checkbox" '+(document.body.classList.contains('reduced')?'checked':'')+'> Reduce motion</label>');case 'expand':return document.querySelectorAll('main details').forEach(d=>d.open=true);case 'practice':{const a=$('input[name=practice]:checked');if(!a)return error('Choose an answer first.');s.practice=Number(a.value);mark(4);Tracker.event('answered','practice',{success:s.practice===c.practice.key,response:String(s.practice)});Tracker.save(s);return feedback((s.practice===c.practice.key?'That fits. ':'Review this decision. ')+c.practice.feedback);}case 'download':if(!s.draft.trim())return error('Write a response before downloading.');download(c.title+'\n\n'+s.draft+'\n\nSelf-review: '+s.criteria.map(i=>c.draft.criteria[i]).join('; '),c.id+'-response.txt');s.exported=true;return;case 'jobaid':return download(c.title+'\n\n'+c.jobaid.join('\n')+'\n\nIndependent portfolio sample.',c.id+'-checklist.txt');case 'keep-tab':$('#dialog').close();mark(5);return go(6);case 'previous-question':qi--;return render();case 'question-next':{const a=$('input[name=quiz]:checked');if(!a)return error('Choose an answer before continuing.');s.answers[qi]=Number(a.value);if(qi<4){qi++;return render();}if(s.answers.some(v=>v===null))return error('Answer all five questions.');const score=c.quiz.reduce((n,v,i)=>n+(s.answers[i]===v.key?20:0),0);s.attempts.push({score,answers:[...s.answers]});c.quiz.forEach((v,i)=>Tracker.event('answered','q-'+i,{success:s.answers[i]===v.key,response:String(s.answers[i])}));Tracker.score(score);mark(6);return go(7);}case 'retry':s.answers.fill(null);qi=0;return go(6);case 'retry-delivery':return Tracker.retry();}});
document.addEventListener('input',e=>{if(e.target.id==='draft'){s.draft=e.target.value;s.exported=false;s.seen=s.seen.filter(n=>![5,9].includes(n));}if($('#error'))$('#error').textContent='';});document.addEventListener('change',e=>{if(e.target.hasAttribute('data-criterion')){const n=Number(e.target.dataset.criterion);s.criteria=s.criteria.filter(v=>v!==n);if(e.target.checked)s.criteria.push(n);s.seen=s.seen.filter(n=>![5,9].includes(n));}if(e.target.id==='large')document.body.classList.toggle('large',e.target.checked);if(e.target.id==='reduced')document.body.classList.toggle('reduced',e.target.checked);if(e.target.name==='quiz')s.answers[qi]=Number(e.target.value);});window.addEventListener('beforeunload',e=>{if(s.draft&&!s.exported){e.preventDefault();e.returnValue='';}});
document.body.classList.add('mood-'+c.creative.visual);$('#brand').textContent=c.brand.name;$('#course-title').textContent=c.title;document.title=c.title;render(false);Tracker.init().then(saved=>{if(saved&&saved.v===1&&saved.course===c.id&&Number.isInteger(saved.step)&&saved.step>=0&&saved.step<10&&Array.isArray(saved.seen)&&Array.isArray(saved.answers)&&Array.isArray(saved.attempts)){s={...s,...saved,draft:'',criteria:[],exported:false};s.seen=s.seen.filter(n=>Number.isInteger(n)&&n>=0&&n<9&&n!==5);render();}});
})();
