window.Experience=(()=>{
const c=COURSE, e=s=>String(s).replace(/[&<>"']/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[a]));
let picks=new Set(),boardReady=false,after=false;
const labHead=(tag,title,desc)=>`<section class="lab" aria-label="Interactive rehearsal"><p class="eyebrow">${tag} / UNGRADED REHEARSAL</p><h2>${title}</h2><p>${desc}</p>`;
const output='<div id="lab-feedback" class="lab-feedback" role="status">Explore the evidence, then make your move.</div></section>';
function lab(){switch(c.id){
case'adkar':return labHead('COACHING CONSOLE','Hear the person behind the change.','Select each evidence card. Then choose support for Jordan’s observed barrier.')+`<div class="evidence-tabs"><button data-evidence="reason">Why change?</button><button data-evidence="steps">Can explain it?</button><button data-evidence="try">Can do it?</button></div><blockquote id="evidence-quote">Jordan is learning a new quality-review workflow. What evidence do you need?</blockquote><div class="actions"><button data-lab-answer="repeat">Assign the same course again</button><button data-lab-answer="coach">Coach a practice case</button><button data-lab-answer="reward">Offer a completion badge</button></div>`+output;
case'adult-learning':return labHead('ACTIVITY BUILDER','Build a 12-minute learning moment.','Choose a starting point, then add practice and feedback. The sequence below responds to your choices.')+`<div class="builder-options"><button data-build="case">3 min · Discuss a real work case</button><button data-build="lecture">3 min · Read the procedure aloud</button><button data-build="practice">6 min · Apply the quality rubric</button><button data-build="feedback">3 min · Compare, revise, plan transfer</button></div><div id="activity-sequence" class="activity-sequence">Your learning sequence appears here.</div><button data-lab-answer="review-design" class="primary">Review my design</button>`+output;
case'ebitda':return labHead('RECONCILIATION BENCH','Build the $190,000 bridge.','Start with $120,000 net income. Select the expenses already deducted in arriving at it. This is a fictional, simplified dataset.')+`<div class="bridge-control"><div class="number-result"><span>YOUR EBITDA / $000</span><strong id="bridge-value">120</strong></div><div class="addbacks">${[['Interest',20],['Income taxes',30],['Depreciation',15],['Amortization',5]].map(([n,v])=>`<label><input type="checkbox" data-addback="${v}">${n} <b>+${v}</b></label>`).join('')}</div></div><button data-lab-answer="cash">Can I spend this amount?</button>`+output;
case'sap-fieldglass':return labHead('EVIDENCE REVIEW','Find the discrepancy before deciding.','Fictional record DEMO-024: five daily entries show 8 hours each. The submitted total claims 42 hours. No approved adjustment is supplied.')+`<div class="review-lab"><table><caption>Daily evidence · fictional week</caption><thead><tr><th scope="col">Day</th><th scope="col">Hours</th><th scope="col">Evidence</th></tr></thead><tbody>${['Monday','Tuesday','Wednesday','Thursday','Friday'].map(n=>`<tr><th scope="row">${n}</th><td>8</td><td>Recorded daily entry</td></tr>`).join('')}</tbody><tfoot><tr><th>Daily total</th><td>40</td><td>Claimed total: 42</td></tr></tfoot></table><div><p class="eyebrow">YOUR REVIEW DECISION</p><button data-lab-answer="approve">Approve the submitted 42 hours</button><button data-lab-answer="correct">Return with a precise correction request</button><button data-lab-answer="edit">Change the record without clarification</button></div></div>`+output;
case'jira-cloud':return labHead('WORKBOARD SIMULATION','Make the handoff testable.','A card says “Fix export.” Add the missing evidence before moving it to Ready for review. Conceptual board; not a reproduction of your organization’s configuration.')+`<div class="sim-board"><div><span>IN PROGRESS</span><article id="sim-ticket"><small>DEMO-41</small><h3>Fix export</h3><p id="ticket-detail">No expected result, observed result or test evidence.</p></article></div><div id="ready-lane"><span>READY FOR REVIEW</span></div></div><div class="actions"><button data-lab-answer="add-evidence">Add acceptance evidence</button><button data-lab-answer="move-card">Move to review →</button></div>`+output;
case'confluence-cloud':return labHead('PAGE MAKEOVER','Make the next reader’s job easier.','Compare the draft with a structured job aid. Then decide how to release it to the intended audience.')+`<div class="actions"><button data-page="before" aria-pressed="true">Before · scattered notes</button><button data-page="after" aria-pressed="false">After · usable guidance</button></div><article id="page-preview" class="page-preview"><h3>Export notes</h3><p>Sometimes slow. Refresh? Ask Morgan.</p><p class="meta">No reader, owner, decision criteria or review trigger.</p></article><div class="actions"><button data-lab-answer="publish-all">Publish to everyone now</button><button data-lab-answer="review-access">Check audience and peer review first</button></div>`+output;
}}
function media(){return `<details class="companion"><summary><span class="play-icon" aria-hidden="true">▶</span> Watch a narrated companion scenario <small>Optional · captioned · separate fictional case</small></summary><p>The film comes from the existing Read/Watch catalog. Its fictional setting may differ from this branded lesson. Use it to compare the underlying decision.</p><video controls preload="none" playsinline poster="${c.mediaBase}.jpg" aria-label="Narrated companion scenario"><source src="${c.mediaBase}.mp4" type="video/mp4"><track kind="captions" src="companion.vtt" srclang="en" label="English" default></video><p class="meta">Video does not start automatically. It does not affect your score or completion.</p><details><summary>Companion question · suggested response</summary><p>${e(c.creative.answer)}</p></details><details><summary>Read the complete transcript</summary><div class="transcript">${e(c.transcript).replaceAll('\n','<br>')}</div></details><p><a href="${c.mediaBase}.mp4" target="_blank" rel="noopener">Open the video separately</a> · <a href="companion.txt" download>Download transcript</a></p></details>`;}
function feedback(s){let el=document.querySelector('#lab-feedback');if(el)el.textContent=s;}
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;
if(b.dataset.evidence){const quotes={reason:'“I understand why consistent reviews matter, and I want to use the new workflow.” → Evidence for Awareness and Desire.',steps:'“I can describe each review step accurately.” → Evidence for Knowledge.',try:'“When I try a case, my ratings do not match the rubric.” → Investigate Ability through observation.'};document.querySelector('#evidence-quote').textContent=quotes[b.dataset.evidence];}
if(b.dataset.build){const k=b.dataset.build;if(picks.has(k))picks.delete(k);else picks.add(k);b.setAttribute('aria-pressed',picks.has(k));document.querySelector('#activity-sequence').innerHTML=[...picks].map((x,i)=>`<span><b>${i+1}</b> ${({case:'Connect to experience',lecture:'Read the procedure',practice:'Apply the rubric',feedback:'Feedback & transfer'})[x]}</span>`).join('')||'Your learning sequence appears here.';}
if(b.dataset.page){after=b.dataset.page==='after';document.querySelectorAll('[data-page]').forEach(x=>x.setAttribute('aria-pressed',x===b));document.querySelector('#page-preview').innerHTML=after?'<small>SUPPORT / RUNBOOKS · FICTIONAL</small><h3>Check a delayed demo export</h3><p><b>Reader:</b> New support analyst</p><ol><li>Check whether the job is still processing in the demo queue.</li><li>Compare elapsed time with the documented team threshold.</li><li>If the threshold is exceeded, escalate with the job ID and observed status.</li></ol><p><b>Owner:</b> Support Knowledge Owner<br><b>Review trigger:</b> Workflow change</p>':'<h3>Export notes</h3><p>Sometimes slow. Refresh? Ask Morgan.</p><p class="meta">No reader, owner, decision criteria or review trigger.</p>';}
if(!b.dataset.labAnswer)return;
switch(b.dataset.labAnswer){case'coach':feedback('A good fit: observe Jordan using the rubric, provide specific feedback, and try another case independently. Recheck the barrier rather than labeling the person.');break;case'repeat':feedback('Jordan can explain the steps. Repeating the same information may not address the observed performance gap. Try coached practice.');break;case'reward':feedback('Recognition can reinforce behavior, but a badge does not establish the ability to apply the rubric.');break;
case'review-design':feedback(picks.has('case')&&picks.has('practice')&&picks.has('feedback')&&!picks.has('lecture')?'A focused 12-minute design: meaningful case, application, feedback and transfer planning. Check the audience’s needs and adapt the timing.':'Check relevance, application and feedback. Choose the case, rubric practice and compare/revise sequence for a focused 12-minute version.');break;
case'cash':feedback('No. EBITDA is an earnings measure. Inspect cash flow, working-capital requirements and funding commitments before deciding what is available to spend.');break;
case'correct':feedback('Return a specific query: “The five daily entries total 40 hours; the submitted total is 42. Please reconcile the difference and resubmit with supporting detail.” Follow the authorized workflow.');break;case'approve':feedback('The evidence does not yet support 42 hours. Reconcile the discrepancy before approving.');break;case'edit':feedback('Do not silently change someone else’s claim. Use the authorized correction route and leave a clear explanation.');break;
case'add-evidence':boardReady=true;document.querySelector('#ticket-detail').textContent='Demo build 2.4: 12 rows on screen, 10 in CSV. Expected: all 12 exported. Reproduced twice. Review: compare output with the synthetic dataset.';feedback('Evidence added. The reviewer now has an expected result, an observed result and a way to check the fix.');break;
case'move-card':if(!boardReady){feedback('Clarify the card first. A status change cannot substitute for acceptance evidence.');break;}document.querySelector('#ready-lane').append(document.querySelector('#sim-ticket'));feedback('Ready for review. This handoff is not a claim that the defect has been verified or closed.');break;
case'publish-all':feedback('First check the intended audience, sensitive content and peer review. Broad access is not always appropriate.');break;case'review-access':feedback('A sound release decision: peer-review the instructions, verify the reader’s access and set ownership and maintenance. Use your team’s publishing process.');break;
}});
document.addEventListener('change',ev=>{if(ev.target.dataset.addback){let value=120;document.querySelectorAll('[data-addback]:checked').forEach(x=>value+=Number(x.dataset.addback));document.querySelector('#bridge-value').textContent=value;feedback(value===190?'Bridge complete: 120 + 20 + 30 + 15 + 5 = 190. Each expense is added once.':'Select each listed expense once. The amounts share one period and unit.');}});
return {mount(step){if(step===1){document.querySelector('.fade>h1').insertAdjacentHTML('afterend',`<p class="role-note"><b>Your delivery lens</b><br>${e(c.creative.role)}</p>`);}if(step===2)document.querySelector('#error').insertAdjacentHTML('beforebegin',media());if(step===3)document.querySelector('#error').insertAdjacentHTML('beforebegin',lab());if(step===0){document.querySelector('.hero').insertAdjacentHTML('afterend',`<div class="experience-strip"><span>01 / See the work</span><span>02 / Rehearse a decision</span><span>03 / Explain your choice</span></div>`);} },reset(){picks.clear();boardReady=false;after=false;}};
})();
