window.Experience=(()=>{
const c=COURSE, e=s=>String(s).replace(/[&<>"']/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[a]));
let picks=new Set(),boardReady=false,after=false;
const labHead=(tag,title,desc)=>`<section class="lab" aria-label="Interactive rehearsal"><p class="eyebrow">${tag} / UNGRADED REHEARSAL</p><h2>${title}</h2><p>${desc}</p>`;
const output='<div id="lab-feedback" class="lab-feedback" role="status">Explore the evidence, then make your move.</div></section>';
function lab(){switch(c.id){
case'adkar':return labHead('COACHING CONSOLE','Hear the person behind the change.','Select each evidence card. Then choose support for Jordan’s observed barrier.')+`<div class="evidence-tabs"><button data-evidence="reason">Why change?</button><button data-evidence="steps">Can explain it?</button><button data-evidence="try">Can do it?</button></div><blockquote id="evidence-quote">Jordan is learning a new quality-review workflow. What evidence do you need?</blockquote><div class="actions"><button data-lab-answer="repeat">Assign the same course again</button><button data-lab-answer="coach">Coach a practice case</button><button data-lab-answer="reward">Offer a completion badge</button></div>`+output;
case'adult-learning':return labHead('ACTIVITY BUILDER','Build a 12-minute learning moment.','Choose a starting point, then add practice and feedback. The sequence below responds to your choices.')+`<div class="builder-options"><button data-build="case">3 min · Discuss a real work case</button><button data-build="lecture">3 min · Read the procedure aloud</button><button data-build="practice">6 min · Apply the quality rubric</button><button data-build="feedback">3 min · Compare, revise, plan transfer</button></div><div id="activity-sequence" class="activity-sequence">Your learning sequence appears here.</div><button data-lab-answer="review-design" class="primary">Review my design</button>`+output;
case'ebitda':return labHead('RECONCILIATION BENCH','Build the $190,000 bridge.','Start with $120,000 net income. Select the expenses already deducted in arriving at it. This is a fictional, simplified dataset.')+`<div class="bridge-control"><div class="number-result"><span>YOUR EBITDA / $000</span><strong id="bridge-value">120</strong></div><div class="addbacks">${[['Interest',20],['Income taxes',30],['Depreciation',15],['Amortization',5]].map(([n,v])=>`<label><input type="checkbox" data-addback="${v}">${n} <b>+${v}</b></label>`).join('')}</div></div><button data-lab-answer="cash">Can I spend this amount?</button>`+output;
case'sap-fieldglass':return labHead('YOUR REVIEW DESK','One record. One decision.','Open both documents. Find the mismatch, then choose your next action. This is a fictional task simulation, not a replica of your tenant.')+`<div class="desk-toolbar"><span><b>FG-204</b> · Casey Lee · 5–9 October</span><span class="desk-status" id="desk-status">Pending review</span></div><div class="document-tabs"><button data-document="sheet" aria-pressed="true">▤ Submitted time sheet</button><button data-document="evidence" aria-pressed="false">▧ Authorized work record</button></div><div id="desk-document" class="desk-document"><p class="eyebrow" id="document-label">SUBMITTED TIME SHEET</p><div class="hours-grid">${['Mon','Tue','Wed','Thu','Fri'].map((day,i)=>`<button data-day="${i}" aria-label="Inspect ${day}"><span>${day}</span><strong data-hours="${i}">8</strong><small>hours</small></button>`).join('')}</div><p id="document-total" class="document-total">Submitted total <strong>40 hours</strong></p><div id="day-evidence" role="status">Select a day to inspect its evidence.</div></div><div class="review-actions"><p class="eyebrow">WHAT DO YOU DO NEXT?</p><div class="actions"><button data-lab-answer="approve">Approve</button><button data-lab-answer="correct" class="primary">Return for correction</button><button data-lab-answer="edit">Edit it yourself</button></div></div>`+output;
case'jira-cloud':return labHead('WORKBOARD SIMULATION','Make the handoff testable.','A card says “Fix export.” Add the missing evidence before moving it to Ready for review. Conceptual board; not a reproduction of your organization’s configuration.')+`<div class="sim-board"><div><span>IN PROGRESS</span><article id="sim-ticket"><small>DEMO-41</small><h3>Fix export</h3><p id="ticket-detail">No expected result, observed result or test evidence.</p></article></div><div id="ready-lane"><span>READY FOR REVIEW</span></div></div><div class="actions"><button data-lab-answer="add-evidence">Add acceptance evidence</button><button data-lab-answer="move-card">Move to review →</button></div>`+output;
case'confluence-cloud':return labHead('PAGE MAKEOVER','Make the next reader’s job easier.','Compare the draft with a structured job aid. Then decide how to release it to the intended audience.')+`<div class="actions"><button data-page="before" aria-pressed="true">Before · scattered notes</button><button data-page="after" aria-pressed="false">After · usable guidance</button></div><article id="page-preview" class="page-preview"><h3>Export notes</h3><p>Sometimes slow. Refresh? Ask Morgan.</p><p class="meta">No reader, owner, decision criteria or review trigger.</p></article><div class="actions"><button data-lab-answer="publish-all">Publish to everyone now</button><button data-lab-answer="review-access">Check audience and peer review first</button></div>`+output;
}}
function media(){return `<section class="watch-stage" aria-label="Watch the narrated scenario"><div class="watch-title"><div><p class="eyebrow">WATCH / LISTEN / NOTICE</p><h2>Before you approve, know what you’re looking at.</h2></div><span class="film-tag">NARRATED SCENARIO</span></div><video controls preload="metadata" playsinline poster="${c.mediaBase}.jpg" aria-label="Narrated time-sheet review scenario"><source src="${c.mediaBase}.mp4" type="video/mp4"><track kind="captions" src="companion.vtt" srclang="en" label="English" default></video><p class="meta">Sound on when you press play · English captions · Fictional Northstar case</p><details><summary>Prefer to read? Full narration and visual context</summary><p>This scenario asks you to distinguish two time sheets by worker, assignment and period. All identifiers and decision evidence are included below.</p><div class="transcript">${e(c.transcript).replaceAll('\n','<br>')}</div><p>${e(c.creative.answer)}</p></details></section>`;}
function feedback(s){let el=document.querySelector('#lab-feedback');if(el)el.textContent=s;}
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;
if(b.dataset.document){const evidence=b.dataset.document==='evidence';document.querySelectorAll('[data-document]').forEach(x=>x.setAttribute('aria-pressed',x===b));document.querySelector('#document-label').textContent=evidence?'AUTHORIZED WORK RECORD':'SUBMITTED TIME SHEET';document.querySelector('[data-hours="4"]').textContent=evidence?'6':'8';document.querySelector('#document-total').innerHTML=evidence?'Supported total <strong>38 hours</strong>':'Submitted total <strong>40 hours</strong>';document.querySelector('#desk-document').classList.toggle('is-evidence',evidence);document.querySelector('#day-evidence').textContent='Select a day to compare the evidence.';}
if(b.hasAttribute('data-day')){const friday=b.dataset.day==='4';document.querySelectorAll('[data-day]').forEach(x=>x.setAttribute('aria-pressed',x===b));document.querySelector('#day-evidence').textContent=friday?'Friday: submitted 8h · authorized 6h. Two hours need clarification.':'This day matches: submitted 8h · authorized 8h.';}
if(b.dataset.evidence){const quotes={reason:'“I understand why consistent reviews matter, and I want to use the new workflow.” → Evidence for Awareness and Desire.',steps:'“I can describe each review step accurately.” → Evidence for Knowledge.',try:'“When I try a case, my ratings do not match the rubric.” → Investigate Ability through observation.'};document.querySelector('#evidence-quote').textContent=quotes[b.dataset.evidence];}
if(b.dataset.build){const k=b.dataset.build;if(picks.has(k))picks.delete(k);else picks.add(k);b.setAttribute('aria-pressed',picks.has(k));document.querySelector('#activity-sequence').innerHTML=[...picks].map((x,i)=>`<span><b>${i+1}</b> ${({case:'Connect to experience',lecture:'Read the procedure',practice:'Apply the rubric',feedback:'Feedback & transfer'})[x]}</span>`).join('')||'Your learning sequence appears here.';}
if(b.dataset.page){after=b.dataset.page==='after';document.querySelectorAll('[data-page]').forEach(x=>x.setAttribute('aria-pressed',x===b));document.querySelector('#page-preview').innerHTML=after?'<small>SUPPORT / RUNBOOKS · FICTIONAL</small><h3>Check a delayed demo export</h3><p><b>Reader:</b> New support analyst</p><ol><li>Check whether the job is still processing in the demo queue.</li><li>Compare elapsed time with the documented team threshold.</li><li>If the threshold is exceeded, escalate with the job ID and observed status.</li></ol><p><b>Owner:</b> Support Knowledge Owner<br><b>Review trigger:</b> Workflow change</p>':'<h3>Export notes</h3><p>Sometimes slow. Refresh? Ask Morgan.</p><p class="meta">No reader, owner, decision criteria or review trigger.</p>';}
if(!b.dataset.labAnswer)return;
switch(b.dataset.labAnswer){case'coach':feedback('A good fit: observe Jordan using the rubric, provide specific feedback, and try another case independently. Recheck the barrier rather than labeling the person.');break;case'repeat':feedback('Jordan can explain the steps. Repeating the same information may not address the observed performance gap. Try coached practice.');break;case'reward':feedback('Recognition can reinforce behavior, but a badge does not establish the ability to apply the rubric.');break;
case'review-design':feedback(picks.has('case')&&picks.has('practice')&&picks.has('feedback')&&!picks.has('lecture')?'A focused 12-minute design: meaningful case, application, feedback and transfer planning. Check the audience’s needs and adapt the timing.':'Check relevance, application and feedback. Choose the case, rubric practice and compare/revise sequence for a focused 12-minute version.');break;
case'cash':feedback('No. EBITDA is an earnings measure. Inspect cash flow, working-capital requirements and funding commitments before deciding what is available to spend.');break;
case'correct':document.querySelector('#desk-status').textContent='Returned for correction';feedback('Good decision. Friday claims 8 hours; the authorized record supports 6. The total is 40 versus 38. Your next task is to write a specific correction request. No real record has been changed.');break;case'approve':document.querySelector('#desk-status').textContent='Approval not supported';feedback('Consequence: approving would accept two hours without supporting evidence. Reopen the authorized work record and inspect Friday, then try again.');break;case'edit':document.querySelector('#desk-status').textContent='Correction route needed';feedback('Consequence: silently changing the claim removes the worker’s opportunity to explain or correct it. Return a precise query through the authorized workflow. Try again.');break;
case'add-evidence':boardReady=true;document.querySelector('#ticket-detail').textContent='Demo build 2.4: 12 rows on screen, 10 in CSV. Expected: all 12 exported. Reproduced twice. Review: compare output with the synthetic dataset.';feedback('Evidence added. The reviewer now has an expected result, an observed result and a way to check the fix.');break;
case'move-card':if(!boardReady){feedback('Clarify the card first. A status change cannot substitute for acceptance evidence.');break;}document.querySelector('#ready-lane').append(document.querySelector('#sim-ticket'));feedback('Ready for review. This handoff is not a claim that the defect has been verified or closed.');break;
case'publish-all':feedback('First check the intended audience, sensitive content and peer review. Broad access is not always appropriate.');break;case'review-access':feedback('A sound release decision: peer-review the instructions, verify the reader’s access and set ownership and maintenance. Use your team’s publishing process.');break;
}});
document.addEventListener('change',ev=>{if(ev.target.dataset.addback){let value=120;document.querySelectorAll('[data-addback]:checked').forEach(x=>value+=Number(x.dataset.addback));document.querySelector('#bridge-value').textContent=value;feedback(value===190?'Bridge complete: 120 + 20 + 30 + 15 + 5 = 190. Each expense is added once.':'Select each listed expense once. The amounts share one period and unit.');}});
return {mount(step){if(step===1){document.querySelector('.fade>h1').insertAdjacentHTML('afterend',`<details class="role-note"><summary>Scenario context and delivery role</summary><p>${e(c.creative.role)}</p></details>`);}if(step===2)document.querySelector('.fade>h1').insertAdjacentHTML('afterend',media());if(step===3)document.querySelector('.fade>h1').insertAdjacentHTML('afterend',lab());if(step===0){document.querySelector('.hero').outerHTML=`<section class="cinema-hero"><img src="hero-editorial.jpg" alt="Illustrative fictional reviewer comparing a document with a laptop in a bright office"><div class="hero-copy"><p class="eyebrow">THE REVIEW DESK / SAP FIELDGLASS</p><h1>Every hour<br>has a story.</h1><p>Find the evidence.<br>Make a confident decision.</p><div class="actions"><button class="primary" data-next>Begin lesson</button><button data-go="2">▶ Watch the scenario</button></div></div></section>`;document.querySelector('.hero-copy').closest('section').insertAdjacentHTML('afterend',`<div class="experience-strip"><span>01 / See the work</span><span>02 / Rehearse a decision</span><span>03 / Explain your choice</span></div>`);} },reset(){picks.clear();boardReady=false;after=false;}};
})();
